default_platform(:ios)

platform :ios do
  desc "Run iOS unit tests"
  lane :tests do
    run_tests(
        project: "iosApp.xcodeproj",
        devices: ["iPhone 7"],
        derived_data_path: "../build"
    )
  end
  desc "Run linting"
  lane :lint do
  swiftlint(
    executable: './Pods/SwiftLint/swiftlint', 
    mode: :lint,
    config_file: '.swiftlint.yml',
  )
  end
end
